/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/QOgOn36ezu8
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Rubik } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import {
  DropdownMenuTrigger,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuItem,
  DropdownMenuGroup,
  DropdownMenuContent,
  DropdownMenu,
  DropdownMenuRadioItem,
  DropdownMenuRadioGroup,
} from "@/components/ui/dropdown-menu";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import Masonry, { ResponsiveMasonry } from "react-responsive-masonry";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";

export function Component() {
  return (
    <div className="min-h-screen bg-gray-100 dark:bg-gray-900">
      <header className="sticky top-0 z-50 bg-white dark:bg-gray-800 py-4 px-4 md:px-6 shadow">
        <div className="container mx-auto flex items-center justify-between">
          <a className="flex items-center gap-2" href="#">
            <FileMusicIcon className="w-6 h-6" />
            <span className="text-xl font-semibold tracking-tight">
              초금비 노래책
            </span>
          </a>
          <div className="flex items-center gap-4">
            <nav className="hidden md:flex gap-4">
              <a
                className="text-sm font-medium hover:text-gray-900 dark:hover:text-gray-100 transition-colors"
                href="#"
              >
                전체 목록
              </a>
              <a
                className="text-sm font-medium hover:text-gray-900 dark:hover:text-gray-100 transition-colors"
                href="#"
              >
                카테고리별
              </a>
              <a
                className="text-sm font-medium hover:text-gray-900 dark:hover:text-gray-100 transition-colors"
                href="#"
              >
                아티스트별
              </a>
            </nav>
            <form className="relative">
              <SearchIcon className="absolute left-2 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500 dark:text-gray-400" />
              <Input
                className="pl-8 pr-2 py-1 rounded-xl bg-gray-100 dark:bg-gray-700 text-sm border-gray-400"
                placeholder="검색어를 입력해주세요"
                type="search"
              />
            </form>
            <Button className="md:hidden" size="icon" variant="ghost">
              <MenuIcon className="w-6 h-6" />
            </Button>
          </div>
        </div>
      </header>
      <main>
        <section className="py-6 md:pt-12 md:">
          <div className="container mx-auto px-4 md:px-6">
            <div className="flex flex-col md:flex-row items-start justify-between gap-4 mb-4">
              <h2 className="text-2xl md:text-3xl font-bold tracking-tight">
                전체 목록
              </h2>
              <div className="flex items-center gap-4">
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button
                      variant="outline"
                      className="border-gray-400 rounded-xl"
                    >
                      <FilterIcon className="w-4 h-4 mr-2" />
                      필터
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent className="bg-white dark:bg-gray-700 rounded-xl shadow-lg">
                    <DropdownMenuLabel>장르</DropdownMenuLabel>
                    <DropdownMenuSeparator />
                    <DropdownMenuGroup>
                      <DropdownMenuItem>
                        <Label
                          className="flex items-center gap-2 cursor-pointer"
                          htmlFor="genre-rock"
                        >
                          <Checkbox id="genre-rock" />
                          Rock
                        </Label>
                      </DropdownMenuItem>
                      <DropdownMenuItem>
                        <Label
                          className="flex items-center gap-2 cursor-pointer"
                          htmlFor="genre-pop"
                        >
                          <Checkbox id="genre-pop" />
                          Pop
                        </Label>
                      </DropdownMenuItem>
                      <DropdownMenuItem>
                        <Label
                          className="flex items-center gap-2 cursor-pointer"
                          htmlFor="genre-hiphop"
                        >
                          <Checkbox id="genre-hiphop" />
                          Hip-Hop
                        </Label>
                      </DropdownMenuItem>
                    </DropdownMenuGroup>
                    <DropdownMenuSeparator />
                    <DropdownMenuLabel>Mood</DropdownMenuLabel>
                    <DropdownMenuSeparator />
                    <DropdownMenuGroup>
                      <DropdownMenuItem>
                        <Label
                          className="flex items-center gap-2 cursor-pointer"
                          htmlFor="mood-happy"
                        >
                          <Checkbox id="mood-happy" />
                          Happy
                        </Label>
                      </DropdownMenuItem>
                      <DropdownMenuItem>
                        <Label
                          className="flex items-center gap-2 cursor-pointer"
                          htmlFor="mood-sad"
                        >
                          <Checkbox id="mood-sad" />
                          Sad
                        </Label>
                      </DropdownMenuItem>
                      <DropdownMenuItem>
                        <Label
                          className="flex items-center gap-2 cursor-pointer"
                          htmlFor="mood-energetic"
                        >
                          <Checkbox id="mood-energetic" />
                          Energetic
                        </Label>
                      </DropdownMenuItem>
                    </DropdownMenuGroup>
                  </DropdownMenuContent>
                </DropdownMenu>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button
                      variant="outline"
                      className="border-gray-400 rounded-xl"
                    >
                      <ArrowUpDownIcon className="w-4 h-4 mr-2" />
                      정렬
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent className="bg-white dark:bg-gray-700 rounded-xl shadow-lg">
                    <DropdownMenuRadioGroup defaultValue="newest">
                      <DropdownMenuRadioItem value="newest">
                        Newest
                      </DropdownMenuRadioItem>
                      <DropdownMenuRadioItem value="oldest">
                        Oldest
                      </DropdownMenuRadioItem>
                      <DropdownMenuRadioItem value="az">
                        A-Z
                      </DropdownMenuRadioItem>
                      <DropdownMenuRadioItem value="za">
                        Z-A
                      </DropdownMenuRadioItem>
                    </DropdownMenuRadioGroup>
                  </DropdownMenuContent>
                </DropdownMenu>
              </div>
            </div>
            <ResponsiveMasonry
              columnsCountBreakPoints={{ 350: 1, 750: 2, 900: 3 }}
              className="w-full"
            >
              {/* <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"> */}
              <Masonry>
                {
                  // 50개 출력
                  Array.from({ length: 50 }).map((_, index) => (
                    <div
                      key={index}
                      className="flex items-center justify-between gap-4 p-4 rounded-md bg-white dark:bg-gray-700 shadow m-2"
                    >
                      <Collapsible>
                        <div>
                          <CollapsibleTrigger>
                            <div className="flex items-center gap-4">
                              <Button
                                className="p-2"
                                size="icon"
                                variant="ghost"
                              >
                                <PlayIcon className="w-6 h-6" />
                              </Button>
                              <div>
                                <h3 className="text-lg font-semibold">
                                  Song Title
                                </h3>
                                <p className="text-sm text-gray-500 dark:text-gray-400">
                                  Artist Name
                                </p>
                              </div>
                            </div>
                            <p className="text-sm text-gray-500 dark:text-gray-400">
                              3:45
                            </p>
                          </CollapsibleTrigger>
                        </div>

                        <CollapsibleContent>
                          {/* 유튜브, Soundcloud 등 버튼과 노래 설명 이 들어가야 함 */}
                          Lorem ipsum, dolor sit amet consectetur adipisicing
                          elit. Ut quisquam non, illo quaerat impedit minima ex
                          praesentium ratione, cumque obcaecati cum. Laborum,
                          possimus odit harum officiis recusandae sunt. Harum,
                          itaque!
                        </CollapsibleContent>
                      </Collapsible>
                    </div>
                  ))
                }
              </Masonry>
              {/* </div> */}
            </ResponsiveMasonry>
            {/* {
                // 50개 출력
                Array.from({ length: 50 }).map((_, index) => (
                  <div
                    key={index}
                    className="flex items-center justify-between gap-4 p-4 rounded-md bg-white dark:bg-gray-700 shadow"
                  >
                    <div className="flex items-center gap-4">
                      <Button className="p-2" size="icon" variant="ghost">
                        <PlayIcon className="w-6 h-6" />
                      </Button>
                      <div>
                        <h3 className="text-lg font-semibold">Song Title</h3>
                        <p className="text-sm text-gray-500 dark:text-gray-400">
                          Artist Name
                        </p>
                      </div>
                    </div>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      3:45
                    </p>
                  </div>
                ))
              } */}
          </div>
        </section>
      </main>
      <footer className="bg-gray-800 py-6">
        <div className="container mx-auto px-4 md:px-6">
          <p className="text-sm text-gray-400">
            © 2024 Chogeumbi. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}

function ArrowUpDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m21 16-4 4-4-4" />
      <path d="M17 20V4" />
      <path d="m3 8 4-4 4 4" />
      <path d="M7 4v16" />
    </svg>
  );
}

function FileMusicIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="14" cy="16" r="2" />
      <circle cx="6" cy="18" r="2" />
      <path d="M4 12.4V4a2 2 0 0 1 2-2h8.5L20 7.5V20a2 2 0 0 1-2 2h-7.5" />
      <path d="M8 18v-7.7L16 9v7" />
    </svg>
  );
}

function FilterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" />
    </svg>
  );
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}

function PlayIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="6 3 20 12 6 21 6 3" />
    </svg>
  );
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}
